#!/bin/bash

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create symbolic link
create_symlink() {
    local source="$1"
    local target="$2"

    [[ "$source" != /* ]] && source="$DOTFILES_DIR/$source"

    [ ! -e "$source" ] && echo "Source does not exist: $source" && return 1

    if [ -L "$target" ]; then
        if [ "$(readlink "$target")" = "$source" ]; then
            echo "Already linked: $target"
            return 0
        fi

        rm "$target"
    elif [ -e "$target" ]; then
        echo "Target already exists and is not a symlink: $target"
        return 1
    fi

    mkdir -p "$(dirname "$target")"
    ln -s "$source" "$target"
    echo "Linked: $target"
}

# Install Homebrew if not installed
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Installed: homebrew"
else
    echo "Already installed: homebrew"
fi

# Install Homebrew packages
packages=(
  "jq"
  "fzf"
  "zoxide"
  "ripgrep"
  "tldr"
  "wget"
  "nvim"
  "git-delta"
  "ghostty"
  "pure"
  "zsh-patina"
)
for package in "${packages[@]}"; do
    if brew list "$package" &> /dev/null; then
        echo "Already installed: $package"
        continue
    fi

    # Install the package
    brew install "$package" && echo "Installed: $package"

    # Additional setup for specific packages
    if [[ "$package" == "fzf" ]]; then
      $(brew --prefix)/opt/fzf/install
    fi
done

# Update git submodules
git submodule update --init --recursive
echo "Updated: git submodules"

# Create symbolic links
create_symlink ".hushlogin" "$HOME/.hushlogin"
create_symlink ".ideavimrc" "$HOME/.ideavimrc"
create_symlink ".zshrc" "$HOME/.zshrc"
create_symlink "ghostty" "$HOME/.config/ghostty/config"
create_symlink "zsh-autosuggestions" "$HOME/.zsh/zsh-autosuggestions"
create_symlink "fzf-tab" "$HOME/.zsh/fzf-tab"
create_symlink "kickstart.nvim" "$HOME/.config/nvim"

echo "Done!"
